Make the tree node class configurable.
Lightricks/tree-model-js pull request #1
Opened 2017-03-07 13:14 UTC by Ner1Co

2017-03-08 13:59 UTC, byohay requested changes
Round

2017-03-08 13:59 UTC, byohay commented on dist/TreeModel.js
> +    if (!(Node.isPrototypeOf(this.config.nodeClass) || this.config.nodeClass === Node)) {
IMO `!Node.isPrototypeOf(this.config.nodeClass) && this.config.nodeClass !== Node` is more readable.

2017-03-08 13:59 UTC, byohay commented on index.js
> +      throw new TypeError('config.nodeClass must be of type Node or extended Node class.');
Same.

2017-03-08 13:59 UTC, byohay commented on test/test.js
> +    it('should config and parse without errors', function () {
The main test here is checking that the tree is itself a `CustomNodeClass` class, so change the title accordingly.

2017-03-08 13:59 UTC, byohay commented on test/test.js
> +      assert.equal(tree instanceof CustomNodeClass, true);
Just `assert(tree instanceof CustomNodeClass);`

2017-03-08 13:59 UTC, byohay commented on test/test.js
> +      CustomNodeClass.__proto__ = TreeModel.Node;
Maybe you can define that `CustomNodeClass` extends `Node`?

2017-03-08 13:59 UTC, byohay commented on test/test.js
> +      assert.equal(tree instanceof CustomNodeClass, true);
Why not using `isPrototypeOf` here? (I'm because I don't know what's better).

2017-03-08 13:59 UTC, byohay commented on test/test.js
> +      var tree = treeModel.parse({node: "info"});
We should continue with the same variable names, e.g. `id`.

2017-03-08 13:59 UTC, byohay commented on README.md
> +* `nodeClass` - The class that is using for creating the tree nodes, must extend `Node` -  otherwise error is thrown. Default is `Node` itself;
`that is used for creating the tree nodes. Must...`.
`otherwise an error...`

2017-03-08 13:59 UTC, byohay commented on dist/TreeModel.js
> +  TreeModel.Node = Node;
What's this for? Don't you need `TreeModel.Node = this.config.nodeClass`?

2017-03-08 15:40 UTC, Ner1Co commented on test/test.js
> +      CustomNodeClass.__proto__ = TreeModel.Node;
this is the dirty way since it's not ES6 here..

2017-03-09 07:37 UTC, Ner1Co commented on dist/TreeModel.js
> +    if (!(Node.isPrototypeOf(this.config.nodeClass) || this.config.nodeClass === Node)) {
Done.

2017-03-09 07:38 UTC, Ner1Co commented on dist/TreeModel.js
> +  TreeModel.Node = Node;
It's for exposing the class Node outside so we can extend it.

2017-03-09 07:38 UTC, Ner1Co commented on index.js
> +      throw new TypeError('config.nodeClass must be of type Node or extended Node class.');
Done.

2017-03-09 07:40 UTC, Ner1Co commented on test/test.js
> +    it('should config and parse without errors', function () {
Done.

2017-03-09 07:41 UTC, Ner1Co commented on test/test.js
> +      var tree = treeModel.parse({node: "info"});
Done.

2017-03-09 07:44 UTC, Ner1Co commented on README.md
> +* `nodeClass` - The class that is using for creating the tree nodes, must extend `Node` -  otherwise error is thrown. Default is `Node` itself;
Done.

2017-03-09 09:34 UTC, byohay requested changes
F&S

2017-03-09 09:34 UTC, byohay commented on test/test.js
> +      assert.throws(function(){new TreeModel({nodeClass: nodeClass})}, TypeError,
1. The string is the message that is displayed when the assertion fails, not asserting what the message should be. So just remove it.
2. IMO this is more readable:
```js
      assert.throws(
          function () {
            new TreeModel({nodeClass: nodeClass})
          },
          TypeError
      );
```

2017-03-09 09:34 UTC, byohay commented on test/test.js
> +
Remove.

2017-03-09 09:34 UTC, byohay commented on test/test.js
> +      assert.ok(tree instanceof CustomNodeClass);
Just `assert` works for me.

2017-03-09 09:51 UTC, Ner1Co commented on test/test.js
> +
Done.

2017-03-09 09:51 UTC, Ner1Co commented on test/test.js
> +      assert.ok(tree instanceof CustomNodeClass);
Done.

2017-03-09 09:52 UTC, Ner1Co commented on test/test.js
> +      assert.throws(function(){new TreeModel({nodeClass: nodeClass})}, TypeError,
Done.

2017-03-12 14:03 UTC, byohay approved these changes

2017-03-12 14:03 UTC, merged